module.exports = {
    getData(){
        let data = {
            "list":[
                {
                    "title":"个护美妆",
                    "content": [
                        {
                            "classify":"面部护理",
                            "conList":[
                                {
                                    "img":"assets/img/classify/93.png",
                                    "name":"面膜"
                                },
                                {
                                    "img":"assets/img/classify/90.png",
                                    "name":"乳液乳霜"
                                },
                                {
                                    "img":"assets/img/classify/94.png",
                                    "name":"精华"
                                },
                                {
                                    "img":"assets/img/classify/96.png",
                                    "name":"护肤套组"
                                },
                                {
                                    "img":"assets/img/classify/97.png",
                                    "name":"防晒隔离"
                                },
                                {
                                    "img":"assets/img/classify/89.png",
                                    "name":"爽肤水"
                                },
                                {
                                    "img":"assets/img/classify/95.png",
                                    "name":"洁面乳"
                                },
                                {
                                    "img":"assets/img/classify/88.png",
                                    "name":"眼部护理"
                                },
                                {
                                    "img":"assets/img/classify/92.png",
                                    "name":"眼膜"
                                }
                            ]
                        },
                        {
                            "classify":"香水彩妆",
                            "conList":[
                                {
                                    "img":"assets/img/classify/121.png",
                                    "name":"唇膏唇彩"
                                },
                                {
                                    "img":"assets/img/classify/126.png",
                                    "name":"遮瑕"
                                },
                                {
                                    "img":"assets/img/classify/127.png",
                                    "name":"粉底粉饼"
                                },
                                {
                                    "img":"assets/img/classify/125.png",
                                    "name":"睫毛膏"
                                },
                                {
                                    "img":"assets/img/classify/124.png",
                                    "name":"眉笔"
                                },
                                {
                                    "img":"assets/img/classify/122.png",
                                    "name":"眼影/眼线"
                                },
                                {
                                    "img":"assets/img/classify/128.png",
                                    "name":"彩妆工具"
                                },
                                {
                                    "img":"assets/img/classify/127.png",
                                    "name":"卸妆"
                                },
                                {
                                    "img":"assets/img/classify/110.png",
                                    "name":"女士香水"
                                }

                            ]
                        },
                        {
                            "classify":"美发护发",
                            "conList":[
                                {
                                    "img":"assets/img/classify/99.png",
                                    "name":"洗发水"
                                },
                                {
                                    "img":"assets/img/classify/100.png",
                                    "name":"护发素"
                                },
                                {
                                    "img":"assets/img/classify/101.png",
                                    "name":"洗护套装"
                                },
                                {
                                    "img":"assets/img/classify/103.png",
                                    "name":"卷发棒"
                                },
                                {
                                    "img":"assets/img/classify/104.png",
                                    "name":"电吹风"
                                },
                                {
                                    "img":"assets/img/classify/102.png",
                                    "name":"染发"
                                }
                            ]
                        },
                        {
                            "classify":"身体护理",
                            "conList":[
                                {
                                    "img":"assets/img/classify/05889626701031510.jpg",
                                    "name":"私密护理"
                                },
                                {
                                    "img":"assets/img/classify/05889626398551421.jpg",
                                    "name":"手工皂"
                                },
                                {
                                    "img":"assets/img/classify/05889610014611514.jpg",
                                    "name":"美容养颜"
                                },
                                {
                                    "img":"assets/img/classify/05889610872282857.jpg",
                                    "name":"磨砂膏"
                                },
                                {
                                    "img":"assets/img/classify/110.png",
                                    "name":"沐浴露"
                                },
                                {
                                    "img":"assets/img/classify/108.png",
                                    "name":"手足护理"
                                },
                                {
                                    "img":"assets/img/classify/109.png",
                                    "name":"身体乳"
                                },
                                {
                                    "img":"assets/img/classify/105.png",
                                    "name":"香薰精油"
                                },
                                {
                                    "img":"assets/img/classify/113.png",
                                    "name":"卫生巾"
                                },
                                {
                                    "img":"assets/img/classify/106.png",
                                    "name":"纤体瘦身"
                                }
                            ]
                        },
                        {
                            "classify":"美容工具",
                            "conList":[
                                {
                                    "img":"assets/img/classify/137.png",
                                    "name":"美容仪"
                                },
                                {
                                    "img":"assets/img/classify/139.png",
                                    "name":"洁面仪"
                                },
                                {
                                    "img":"assets/img/classify/140.png",
                                    "name":"理发器"
                                },
                                {
                                    "img":"assets/img/classify/133.png",
                                    "name":"剃须刀"
                                },
                                {
                                    "img":"assets/img/classify/132.png",
                                    "name":"剃毛器"
                                },
                                {
                                    "img":"assets/img/classify/134.png",
                                    "name":"喷雾器"
                                },
                                {
                                    "img":"assets/img/classify/138.png",
                                    "name":"美容配件"
                                }
                            ]
                        },
                        {
                            "classify":"口腔护理",
                            "conList":[
                                {
                                    "img":"assets/img/classify/114.png",
                                    "name":"牙刷"
                                },
                                {
                                    "img":"assets/img/classify/115.png",
                                    "name":"牙膏"
                                }
                            ]
                        }
                    ]
                },
                {
                    "title":"食品健康",
                    "content":[
                        {
                            "classify":"饮料冲调",
                            "conList":[
                                {
                                    "img":"assets/img/classify/05912118169295012.jpg",
                                    "name":"牛奶/酸奶"
                                },
                                {
                                    "img":"assets/img/classify/71.png",
                                    "name":"麦片/代餐粉"
                                },
                                {
                                    "img":"assets/img/classify/05912118743188649.jpg",
                                    "name":"蜂蜜"
                                },
                                {
                                    "img":"assets/img/classify/05756605421698748.jpg",
                                    "name":"冲调饮品"
                                },
                                {
                                    "img":"assets/img/classify/68.png",
                                    "name":"红糖/黑糖"
                                },
                                {
                                    "img":"assets/img/classify/70.png",
                                    "name":"咖啡"
                                }
                            ]
                        },
                        {
                            "classify":"粮油调味",
                            "conList":[
                                {
                                    "img":"assets/img/classify/72.png",
                                    "name":"米面"
                                },
                                {
                                    "img":"assets/img/classify/73.png",
                                    "name":"五谷"
                                },
                                {
                                    "img":"assets/img/classify/74.png",
                                    "name":"食用油"
                                },
                                {
                                    "img":"assets/img/classify/05705601004101141.jpg",
                                    "name":"速食食品"
                                },
                                {
                                    "img":"assets/img/classify/76.png",
                                    "name":"南北干货"
                                },
                                {
                                    "img":"assets/img/classify/77.png",
                                    "name":"调料"
                                }
                                ,
                                {
                                    "img":"assets/img/classify/05612086593355496.jpg",
                                    "name":"腊味"
                                }
                            ]
                        },
                        {
                            "classify":"酒水茗茶",
                            "conList":[
                                {
                                    "img":"assets/img/classify/64.png",
                                    "name":"白酒"
                                },
                                {
                                    "img":"assets/img/classify/65.png",
                                    "name":"进口红酒"
                                },
                                {
                                    "img":"assets/img/classify/05596782712795776.jpg",
                                    "name":"国产红酒"
                                },
                                {
                                    "img":"assets/img/classify/05779835045862004.jpg",
                                    "name":"啤酒"
                                },
                                {
                                    "img":"assets/img/classify/62.png",
                                    "name":"黑茶/普洱"
                                },
                                {
                                    "img":"assets/img/classify/61.png",
                                    "name":"红茶/绿茶"
                                },
                                {
                                    "img":"assets/img/classify/63.png",
                                    "name":"花草茶"
                                }
                            ]
                        },
                        {
                            "classify":"休闲食品",
                            "conList":[
                                {
                                    "img":"assets/img/classify/55.png",
                                    "name":"坚果/果干"
                                },
                                {
                                    "img":"assets/img/classify/56.png",
                                    "name":"饼干糕点"
                                },
                                {
                                    "img":"assets/img/classify/57.png",
                                    "name":"糖果/巧克力"
                                },
                                {
                                    "img":"assets/img/classify/58.png",
                                    "name":"零食"
                                },
                                {
                                    "img":"assets/img/classify/59.png",
                                    "name":"麻辣零食"
                                }
                            ]
                        },
                        {
                            "classify":"营养保健",
                            "conList":[
                                {
                                    "img":"assets/img/classify/84.png",
                                    "name":"红枣/枸杞"
                                },
                                {
                                    "img":"assets/img/classify/81.png",
                                    "name":"女性保养"
                                },
                                {
                                    "img":"assets/img/classify/83.png",
                                    "name":"阿胶/燕窝"
                                },
                                {
                                    "img":"assets/img/classify/86.png",
                                    "name":"传统滋补"
                                },
                                {
                                    "img":"assets/img/classify/85.png",
                                    "name":"基础保健"
                                },
                                {
                                    "img":"assets/img/classify/82.png",
                                    "name":"瘦身/酵素"
                                }
                            ]
                        },
                        {
                            "classify":"生鲜食品",
                            "conList":[
                                {
                                    "img":"assets/img/classify/78.png",
                                    "name":"新鲜果蔬"
                                },
                                {
                                    "img":"assets/img/classify/79.png",
                                    "name":"肉类"
                                },
                                {
                                    "img":"assets/img/classify/80.png",
                                    "name":"家禽蛋类"
                                },
                                {
                                    "img":"assets/img/classify/05596782259518399.jpg",
                                    "name":"大闸蟹"
                                },
                                {
                                    "img":"assets/img/classify/05612341740621245.jpg",
                                    "name":"生鲜水产"
                                }
                            ]
                        }
                    ]
                },
                {
                    "title":"餐厨日用",
                    "content":[
                        {
                            "classify":"厨房电器",
                            "conList":[
                                {
                                    "img":"assets/img/classify/93.png",
                                    "name":"面膜"
                                },
                                {
                                    "img":"assets/img/classify/90.png",
                                    "name":"乳液乳霜"
                                },
                                {
                                    "img":"assets/img/classify/94.png",
                                    "name":"精华"
                                },
                                {
                                    "img":"assets/img/classify/96.png",
                                    "name":"护肤套组"
                                },
                                {
                                    "img":"assets/img/classify/97.png",
                                    "name":"防晒隔离"
                                },
                                {
                                    "img":"assets/img/classify/89.png",
                                    "name":"爽肤水"
                                },
                                {
                                    "img":"assets/img/classify/95.png",
                                    "name":"洁面乳"
                                },
                                {
                                    "img":"assets/img/classify/88.png",
                                    "name":"眼部护理"
                                },
                                {
                                    "img":"assets/img/classify/92.png",
                                    "name":"眼膜"
                                }
                            ]
                        },
                        {
                            "classify":"健康保健",
                            "conList":[
                                {
                                    "img":"assets/img/classify/93.png",
                                    "name":"面膜"
                                },
                                {
                                    "img":"assets/img/classify/90.png",
                                    "name":"乳液乳霜"
                                },
                                {
                                    "img":"assets/img/classify/94.png",
                                    "name":"精华"
                                },
                                {
                                    "img":"assets/img/classify/96.png",
                                    "name":"护肤套组"
                                },
                                {
                                    "img":"assets/img/classify/97.png",
                                    "name":"防晒隔离"
                                },
                                {
                                    "img":"assets/img/classify/89.png",
                                    "name":"爽肤水"
                                },
                                {
                                    "img":"assets/img/classify/95.png",
                                    "name":"洁面乳"
                                },
                                {
                                    "img":"assets/img/classify/88.png",
                                    "name":"眼部护理"
                                },
                                {
                                    "img":"assets/img/classify/92.png",
                                    "name":"眼膜"
                                }
                            ]
                        },
                        {
                            "classify":"烹饪锅具",
                            "conList":[
                                {
                                    "img":"assets/img/classify/93.png",
                                    "name":"面膜"
                                },
                                {
                                    "img":"assets/img/classify/90.png",
                                    "name":"乳液乳霜"
                                },
                                {
                                    "img":"assets/img/classify/94.png",
                                    "name":"精华"
                                },
                                {
                                    "img":"assets/img/classify/96.png",
                                    "name":"护肤套组"
                                },
                                {
                                    "img":"assets/img/classify/97.png",
                                    "name":"防晒隔离"
                                },
                                {
                                    "img":"assets/img/classify/89.png",
                                    "name":"爽肤水"
                                },
                                {
                                    "img":"assets/img/classify/95.png",
                                    "name":"洁面乳"
                                },
                                {
                                    "img":"assets/img/classify/88.png",
                                    "name":"眼部护理"
                                },
                                {
                                    "img":"assets/img/classify/92.png",
                                    "name":"眼膜"
                                }
                            ]
                        },
                        {
                            "classify":"厨房用具",
                            "conList":[
                                {
                                    "img":"assets/img/classify/93.png",
                                    "name":"面膜"
                                },
                                {
                                    "img":"assets/img/classify/90.png",
                                    "name":"乳液乳霜"
                                },
                                {
                                    "img":"assets/img/classify/94.png",
                                    "name":"精华"
                                },
                                {
                                    "img":"assets/img/classify/96.png",
                                    "name":"护肤套组"
                                },
                                {
                                    "img":"assets/img/classify/97.png",
                                    "name":"防晒隔离"
                                },
                                {
                                    "img":"assets/img/classify/89.png",
                                    "name":"爽肤水"
                                },
                                {
                                    "img":"assets/img/classify/95.png",
                                    "name":"洁面乳"
                                },
                                {
                                    "img":"assets/img/classify/88.png",
                                    "name":"眼部护理"
                                },
                                {
                                    "img":"assets/img/classify/92.png",
                                    "name":"眼膜"
                                }
                            ]
                        },
                        {
                            "classify":"清洁收纳",
                            "conList":[
                                {
                                    "img":"assets/img/classify/93.png",
                                    "name":"面膜"
                                },
                                {
                                    "img":"assets/img/classify/90.png",
                                    "name":"乳液乳霜"
                                },
                                {
                                    "img":"assets/img/classify/94.png",
                                    "name":"精华"
                                },
                                {
                                    "img":"assets/img/classify/96.png",
                                    "name":"护肤套组"
                                },
                                {
                                    "img":"assets/img/classify/97.png",
                                    "name":"防晒隔离"
                                },
                                {
                                    "img":"assets/img/classify/89.png",
                                    "name":"爽肤水"
                                },
                                {
                                    "img":"assets/img/classify/95.png",
                                    "name":"洁面乳"
                                },
                                {
                                    "img":"assets/img/classify/88.png",
                                    "name":"眼部护理"
                                },
                                {
                                    "img":"assets/img/classify/92.png",
                                    "name":"眼膜"
                                }
                            ]
                        },
                    ]
                },
                {
                    "title":"服装配饰",
                    "content":[
                        {
                            "classify":"女士服装",
                            "conList":[
                                {
                                    "img":"assets/img/classify/05912118169295012.jpg",
                                    "name":"牛奶/酸奶"
                                },
                                {
                                    "img":"assets/img/classify/71.png",
                                    "name":"麦片/代餐粉"
                                },
                                {
                                    "img":"assets/img/classify/05912118743188649.jpg",
                                    "name":"蜂蜜"
                                },
                                {
                                    "img":"assets/img/classify/05756605421698748.jpg",
                                    "name":"冲调饮品"
                                },
                                {
                                    "img":"assets/img/classify/68.png",
                                    "name":"红糖/黑糖"
                                },
                                {
                                    "img":"assets/img/classify/70.png",
                                    "name":"咖啡"
                                }
                            ]
                        },
                        {
                            "classify":"男士服装",
                            "conList":[
                                {
                                    "img":"assets/img/classify/72.png",
                                    "name":"米面"
                                },
                                {
                                    "img":"assets/img/classify/73.png",
                                    "name":"五谷"
                                },
                                {
                                    "img":"assets/img/classify/74.png",
                                    "name":"食用油"
                                },
                                {
                                    "img":"assets/img/classify/05705601004101141.jpg",
                                    "name":"速食食品"
                                },
                                {
                                    "img":"assets/img/classify/76.png",
                                    "name":"南北干货"
                                },
                                {
                                    "img":"assets/img/classify/77.png",
                                    "name":"调料"
                                }
                                ,
                                {
                                    "img":"assets/img/classify/05612086593355496.jpg",
                                    "name":"腊味"
                                }
                            ]
                        },
                        {
                            "classify":"内衣",
                            "conList":[
                                {
                                    "img":"assets/img/classify/64.png",
                                    "name":"白酒"
                                },
                                {
                                    "img":"assets/img/classify/65.png",
                                    "name":"进口红酒"
                                },
                                {
                                    "img":"assets/img/classify/05596782712795776.jpg",
                                    "name":"国产红酒"
                                },
                                {
                                    "img":"assets/img/classify/05779835045862004.jpg",
                                    "name":"啤酒"
                                },
                                {
                                    "img":"assets/img/classify/62.png",
                                    "name":"黑茶/普洱"
                                },
                                {
                                    "img":"assets/img/classify/61.png",
                                    "name":"红茶/绿茶"
                                },
                                {
                                    "img":"assets/img/classify/63.png",
                                    "name":"花草茶"
                                }
                            ]
                        },
                        {
                            "classify":"鞋靴",
                            "conList":[
                                {
                                    "img":"assets/img/classify/55.png",
                                    "name":"坚果/果干"
                                },
                                {
                                    "img":"assets/img/classify/56.png",
                                    "name":"饼干糕点"
                                },
                                {
                                    "img":"assets/img/classify/57.png",
                                    "name":"糖果/巧克力"
                                },
                                {
                                    "img":"assets/img/classify/58.png",
                                    "name":"零食"
                                },
                                {
                                    "img":"assets/img/classify/59.png",
                                    "name":"麻辣零食"
                                }
                            ]
                        },
                        {
                            "classify":"箱包",
                            "conList":[
                                {
                                    "img":"assets/img/classify/84.png",
                                    "name":"红枣/枸杞"
                                },
                                {
                                    "img":"assets/img/classify/81.png",
                                    "name":"女性保养"
                                },
                                {
                                    "img":"assets/img/classify/83.png",
                                    "name":"阿胶/燕窝"
                                },
                                {
                                    "img":"assets/img/classify/86.png",
                                    "name":"传统滋补"
                                },
                                {
                                    "img":"assets/img/classify/85.png",
                                    "name":"基础保健"
                                },
                                {
                                    "img":"assets/img/classify/82.png",
                                    "name":"瘦身/酵素"
                                }
                            ]
                        },
                        {
                            "classify":"眼镜配饰",
                            "conList":[
                                {
                                    "img":"assets/img/classify/78.png",
                                    "name":"新鲜果蔬"
                                },
                                {
                                    "img":"assets/img/classify/79.png",
                                    "name":"肉类"
                                },
                                {
                                    "img":"assets/img/classify/80.png",
                                    "name":"家禽蛋类"
                                },
                                {
                                    "img":"assets/img/classify/05596782259518399.jpg",
                                    "name":"大闸蟹"
                                },
                                {
                                    "img":"assets/img/classify/05612341740621245.jpg",
                                    "name":"生鲜水产"
                                }
                            ]
                        }
                    ]
                },
                {
                    "title":"布艺家纺",
                    "content":[
                        {
                            "classify":"床品套件",
                            "conList":[
                                {
                                    "img":"assets/img/classify/93.png",
                                    "name":"面膜"
                                },
                                {
                                    "img":"assets/img/classify/90.png",
                                    "name":"乳液乳霜"
                                },
                                {
                                    "img":"assets/img/classify/94.png",
                                    "name":"精华"
                                },
                                {
                                    "img":"assets/img/classify/96.png",
                                    "name":"护肤套组"
                                },
                                {
                                    "img":"assets/img/classify/97.png",
                                    "name":"防晒隔离"
                                },
                                {
                                    "img":"assets/img/classify/89.png",
                                    "name":"爽肤水"
                                },
                                {
                                    "img":"assets/img/classify/95.png",
                                    "name":"洁面乳"
                                },
                                {
                                    "img":"assets/img/classify/88.png",
                                    "name":"眼部护理"
                                },
                                {
                                    "img":"assets/img/classify/92.png",
                                    "name":"眼膜"
                                }
                            ]
                        },
                        {
                            "classify":"抱枕靠垫",
                            "conList":[
                                {
                                    "img":"assets/img/classify/93.png",
                                    "name":"面膜"
                                },
                                {
                                    "img":"assets/img/classify/90.png",
                                    "name":"乳液乳霜"
                                },
                                {
                                    "img":"assets/img/classify/94.png",
                                    "name":"精华"
                                },
                                {
                                    "img":"assets/img/classify/96.png",
                                    "name":"护肤套组"
                                },
                                {
                                    "img":"assets/img/classify/97.png",
                                    "name":"防晒隔离"
                                },
                                {
                                    "img":"assets/img/classify/89.png",
                                    "name":"爽肤水"
                                },
                                {
                                    "img":"assets/img/classify/95.png",
                                    "name":"洁面乳"
                                },
                                {
                                    "img":"assets/img/classify/88.png",
                                    "name":"眼部护理"
                                },
                                {
                                    "img":"assets/img/classify/92.png",
                                    "name":"眼膜"
                                }
                            ]
                        },
                        {
                            "classify":"布艺软饰",
                            "conList":[
                                {
                                    "img":"assets/img/classify/93.png",
                                    "name":"面膜"
                                },
                                {
                                    "img":"assets/img/classify/90.png",
                                    "name":"乳液乳霜"
                                },
                                {
                                    "img":"assets/img/classify/94.png",
                                    "name":"精华"
                                },
                                {
                                    "img":"assets/img/classify/96.png",
                                    "name":"护肤套组"
                                },
                                {
                                    "img":"assets/img/classify/97.png",
                                    "name":"防晒隔离"
                                },
                                {
                                    "img":"assets/img/classify/89.png",
                                    "name":"爽肤水"
                                },
                                {
                                    "img":"assets/img/classify/95.png",
                                    "name":"洁面乳"
                                },
                                {
                                    "img":"assets/img/classify/88.png",
                                    "name":"眼部护理"
                                },
                                {
                                    "img":"assets/img/classify/92.png",
                                    "name":"眼膜"
                                }
                            ]
                        },
                        {
                            "classify":"毛巾浴巾",
                            "conList":[
                                {
                                    "img":"assets/img/classify/93.png",
                                    "name":"面膜"
                                },
                                {
                                    "img":"assets/img/classify/90.png",
                                    "name":"乳液乳霜"
                                },
                                {
                                    "img":"assets/img/classify/94.png",
                                    "name":"精华"
                                },
                                {
                                    "img":"assets/img/classify/96.png",
                                    "name":"护肤套组"
                                },
                                {
                                    "img":"assets/img/classify/97.png",
                                    "name":"防晒隔离"
                                },
                                {
                                    "img":"assets/img/classify/89.png",
                                    "name":"爽肤水"
                                },
                                {
                                    "img":"assets/img/classify/95.png",
                                    "name":"洁面乳"
                                },
                                {
                                    "img":"assets/img/classify/88.png",
                                    "name":"眼部护理"
                                },
                                {
                                    "img":"assets/img/classify/92.png",
                                    "name":"眼膜"
                                }
                            ]
                        },
                    ]
                },
                {
                    "title":"家电数码",
                    "content":[
                        {
                            "classify":"生活电器",
                            "conList":[
                                {
                                    "img":"assets/img/classify/05912118169295012.jpg",
                                    "name":"牛奶/酸奶"
                                },
                                {
                                    "img":"assets/img/classify/71.png",
                                    "name":"麦片/代餐粉"
                                },
                                {
                                    "img":"assets/img/classify/05912118743188649.jpg",
                                    "name":"蜂蜜"
                                },
                                {
                                    "img":"assets/img/classify/05756605421698748.jpg",
                                    "name":"冲调饮品"
                                },
                                {
                                    "img":"assets/img/classify/68.png",
                                    "name":"红糖/黑糖"
                                },
                                {
                                    "img":"assets/img/classify/70.png",
                                    "name":"咖啡"
                                }
                            ]
                        },
                        {
                            "classify":"大家电",
                            "conList":[
                                {
                                    "img":"assets/img/classify/72.png",
                                    "name":"米面"
                                },
                                {
                                    "img":"assets/img/classify/73.png",
                                    "name":"五谷"
                                },
                                {
                                    "img":"assets/img/classify/74.png",
                                    "name":"食用油"
                                },
                                {
                                    "img":"assets/img/classify/05705601004101141.jpg",
                                    "name":"速食食品"
                                },
                                {
                                    "img":"assets/img/classify/76.png",
                                    "name":"南北干货"
                                },
                                {
                                    "img":"assets/img/classify/77.png",
                                    "name":"调料"
                                }
                                ,
                                {
                                    "img":"assets/img/classify/05612086593355496.jpg",
                                    "name":"腊味"
                                }
                            ]
                        },
                        {
                            "classify":"手机通讯",
                            "conList":[
                                {
                                    "img":"assets/img/classify/64.png",
                                    "name":"白酒"
                                },
                                {
                                    "img":"assets/img/classify/65.png",
                                    "name":"进口红酒"
                                },
                                {
                                    "img":"assets/img/classify/05596782712795776.jpg",
                                    "name":"国产红酒"
                                },
                                {
                                    "img":"assets/img/classify/05779835045862004.jpg",
                                    "name":"啤酒"
                                },
                                {
                                    "img":"assets/img/classify/62.png",
                                    "name":"黑茶/普洱"
                                },
                                {
                                    "img":"assets/img/classify/61.png",
                                    "name":"红茶/绿茶"
                                },
                                {
                                    "img":"assets/img/classify/63.png",
                                    "name":"花草茶"
                                }
                            ]
                        },
                        {
                            "classify":"电脑影音",
                            "conList":[
                                {
                                    "img":"assets/img/classify/55.png",
                                    "name":"坚果/果干"
                                },
                                {
                                    "img":"assets/img/classify/56.png",
                                    "name":"饼干糕点"
                                },
                                {
                                    "img":"assets/img/classify/57.png",
                                    "name":"糖果/巧克力"
                                },
                                {
                                    "img":"assets/img/classify/58.png",
                                    "name":"零食"
                                },
                                {
                                    "img":"assets/img/classify/59.png",
                                    "name":"麻辣零食"
                                }
                            ]
                        }
                    ]
                },
                {
                    "title":"母婴呵护",
                    "content":[
                        {
                            "classify":"婴幼护理",
                            "conList":[
                                {
                                    "img":"assets/img/classify/93.png",
                                    "name":"面膜"
                                },
                                {
                                    "img":"assets/img/classify/90.png",
                                    "name":"乳液乳霜"
                                },
                                {
                                    "img":"assets/img/classify/94.png",
                                    "name":"精华"
                                },
                                {
                                    "img":"assets/img/classify/96.png",
                                    "name":"护肤套组"
                                },
                                {
                                    "img":"assets/img/classify/97.png",
                                    "name":"防晒隔离"
                                },
                                {
                                    "img":"assets/img/classify/89.png",
                                    "name":"爽肤水"
                                },
                                {
                                    "img":"assets/img/classify/95.png",
                                    "name":"洁面乳"
                                },
                                {
                                    "img":"assets/img/classify/88.png",
                                    "name":"眼部护理"
                                },
                                {
                                    "img":"assets/img/classify/92.png",
                                    "name":"眼膜"
                                }
                            ]
                        },
                        {
                            "classify":"孕童服饰",
                            "conList":[
                                {
                                    "img":"assets/img/classify/93.png",
                                    "name":"面膜"
                                },
                                {
                                    "img":"assets/img/classify/90.png",
                                    "name":"乳液乳霜"
                                },
                                {
                                    "img":"assets/img/classify/94.png",
                                    "name":"精华"
                                },
                                {
                                    "img":"assets/img/classify/96.png",
                                    "name":"护肤套组"
                                },
                                {
                                    "img":"assets/img/classify/97.png",
                                    "name":"防晒隔离"
                                },
                                {
                                    "img":"assets/img/classify/89.png",
                                    "name":"爽肤水"
                                },
                                {
                                    "img":"assets/img/classify/95.png",
                                    "name":"洁面乳"
                                },
                                {
                                    "img":"assets/img/classify/88.png",
                                    "name":"眼部护理"
                                },
                                {
                                    "img":"assets/img/classify/92.png",
                                    "name":"眼膜"
                                }
                            ]
                        },
                        {
                            "classify":"早教玩具",
                            "conList":[
                                {
                                    "img":"assets/img/classify/93.png",
                                    "name":"面膜"
                                },
                                {
                                    "img":"assets/img/classify/90.png",
                                    "name":"乳液乳霜"
                                },
                                {
                                    "img":"assets/img/classify/94.png",
                                    "name":"精华"
                                },
                                {
                                    "img":"assets/img/classify/96.png",
                                    "name":"护肤套组"
                                },
                                {
                                    "img":"assets/img/classify/97.png",
                                    "name":"防晒隔离"
                                },
                                {
                                    "img":"assets/img/classify/89.png",
                                    "name":"爽肤水"
                                },
                                {
                                    "img":"assets/img/classify/95.png",
                                    "name":"洁面乳"
                                },
                                {
                                    "img":"assets/img/classify/88.png",
                                    "name":"眼部护理"
                                },
                                {
                                    "img":"assets/img/classify/92.png",
                                    "name":"眼膜"
                                }
                            ]
                        },
                    ]
                },
                {
                    "title":"芒果汽车",
                    "content":[
                        {
                            "classify":"汽配周边",
                            "conList":[
                                {
                                    "img":"assets/img/classify/05912118169295012.jpg",
                                    "name":"牛奶/酸奶"
                                },
                                {
                                    "img":"assets/img/classify/71.png",
                                    "name":"麦片/代餐粉"
                                },
                                {
                                    "img":"assets/img/classify/05912118743188649.jpg",
                                    "name":"蜂蜜"
                                },
                                {
                                    "img":"assets/img/classify/05756605421698748.jpg",
                                    "name":"冲调饮品"
                                },
                                {
                                    "img":"assets/img/classify/68.png",
                                    "name":"红糖/黑糖"
                                },
                                {
                                    "img":"assets/img/classify/70.png",
                                    "name":"咖啡"
                                }
                            ]
                        }
                    ]
                },
                {
                    "title":"品牌馆",
                    "content":[
                        {
                            "classify":"个护美妆",
                            "conList":[
                                {
                                    "img":"assets/img/classify/93.png",
                                    "name":"面膜"
                                },
                                {
                                    "img":"assets/img/classify/90.png",
                                    "name":"乳液乳霜"
                                },
                                {
                                    "img":"assets/img/classify/94.png",
                                    "name":"精华"
                                },
                                {
                                    "img":"assets/img/classify/96.png",
                                    "name":"护肤套组"
                                },
                                {
                                    "img":"assets/img/classify/97.png",
                                    "name":"防晒隔离"
                                },
                                {
                                    "img":"assets/img/classify/89.png",
                                    "name":"爽肤水"
                                },
                                {
                                    "img":"assets/img/classify/95.png",
                                    "name":"洁面乳"
                                },
                                {
                                    "img":"assets/img/classify/88.png",
                                    "name":"眼部护理"
                                },
                                {
                                    "img":"assets/img/classify/92.png",
                                    "name":"眼膜"
                                }
                            ]
                        },
                        {
                            "classify":"食品健康",
                            "conList":[
                                {
                                    "img":"assets/img/classify/93.png",
                                    "name":"面膜"
                                },
                                {
                                    "img":"assets/img/classify/90.png",
                                    "name":"乳液乳霜"
                                },
                                {
                                    "img":"assets/img/classify/94.png",
                                    "name":"精华"
                                },
                                {
                                    "img":"assets/img/classify/96.png",
                                    "name":"护肤套组"
                                },
                                {
                                    "img":"assets/img/classify/97.png",
                                    "name":"防晒隔离"
                                },
                                {
                                    "img":"assets/img/classify/89.png",
                                    "name":"爽肤水"
                                },
                                {
                                    "img":"assets/img/classify/95.png",
                                    "name":"洁面乳"
                                },
                                {
                                    "img":"assets/img/classify/88.png",
                                    "name":"眼部护理"
                                },
                                {
                                    "img":"assets/img/classify/92.png",
                                    "name":"眼膜"
                                }
                            ]
                        },
                        {
                            "classify":"餐厨日用",
                            "conList":[
                                {
                                    "img":"assets/img/classify/93.png",
                                    "name":"面膜"
                                },
                                {
                                    "img":"assets/img/classify/90.png",
                                    "name":"乳液乳霜"
                                },
                                {
                                    "img":"assets/img/classify/94.png",
                                    "name":"精华"
                                },
                                {
                                    "img":"assets/img/classify/96.png",
                                    "name":"护肤套组"
                                },
                                {
                                    "img":"assets/img/classify/97.png",
                                    "name":"防晒隔离"
                                },
                                {
                                    "img":"assets/img/classify/89.png",
                                    "name":"爽肤水"
                                },
                                {
                                    "img":"assets/img/classify/95.png",
                                    "name":"洁面乳"
                                },
                                {
                                    "img":"assets/img/classify/88.png",
                                    "name":"眼部护理"
                                },
                                {
                                    "img":"assets/img/classify/92.png",
                                    "name":"眼膜"
                                }
                            ]
                        },
                        {
                            "classify":"服装配饰",
                            "conList":[
                                {
                                    "img":"assets/img/classify/93.png",
                                    "name":"面膜"
                                },
                                {
                                    "img":"assets/img/classify/90.png",
                                    "name":"乳液乳霜"
                                },
                                {
                                    "img":"assets/img/classify/94.png",
                                    "name":"精华"
                                },
                                {
                                    "img":"assets/img/classify/96.png",
                                    "name":"护肤套组"
                                },
                                {
                                    "img":"assets/img/classify/97.png",
                                    "name":"防晒隔离"
                                },
                                {
                                    "img":"assets/img/classify/89.png",
                                    "name":"爽肤水"
                                },
                                {
                                    "img":"assets/img/classify/95.png",
                                    "name":"洁面乳"
                                },
                                {
                                    "img":"assets/img/classify/88.png",
                                    "name":"眼部护理"
                                },
                                {
                                    "img":"assets/img/classify/92.png",
                                    "name":"眼膜"
                                }
                            ]
                        },
                    ]
                }
            ]
        }
        return data
    }
}
