module.exports = {
    getData(){
        let data = {
            "list":[
                {
                    "title":"个护美妆",
                    "content": [
                        {
                            "classify":"面部护理",
                            "conList":[
                                {
                                    "img":"assets/img/classify/93.png",
                                    "name":"面膜"
                                },
                                {
                                    "img":"assets/img/classify/90.png",
                                    "name":"乳液乳霜"
                                },
                                {
                                    "img":"assets/img/classify/94.png",
                                    "name":"精华"
                                },
                                {
                                    "img":"assets/img/classify/96.png",
                                    "name":"护肤套组"
                                },
                                {
                                    "img":"assets/img/classify/97.png",
                                    "name":"防晒隔离"
                                },
                                {
                                    "img":"assets/img/classify/89.png",
                                    "name":"爽肤水"
                                },
                                {
                                    "img":"assets/img/classify/95.png",
                                    "name":"洁面乳"
                                },
                                {
                                    "img":"assets/img/classify/88.png",
                                    "name":"眼部护理"
                                },
                                {
                                    "img":"assets/img/classify/92.png",
                                    "name":"眼膜"
                                }
                            ]
                        },
                        {
                            "classify":"香水彩妆",
                            "conList":[
                                {
                                    "img":"assets/img/classify/121.png",
                                    "name":"唇膏唇彩"
                                },
                                {
                                    "img":"assets/img/classify/126.png",
                                    "name":"遮瑕"
                                },
                                {
                                    "img":"assets/img/classify/127.png",
                                    "name":"粉底粉饼"
                                },
                                {
                                    "img":"assets/img/classify/125.png",
                                    "name":"睫毛膏"
                                },
                                {
                                    "img":"assets/img/classify/124.png",
                                    "name":"眉笔"
                                },
                                {
                                    "img":"assets/img/classify/122.png",
                                    "name":"眼影/眼线"
                                },
                                {
                                    "img":"assets/img/classify/128.png",
                                    "name":"彩妆工具"
                                },
                                {
                                    "img":"assets/img/classify/127.png",
                                    "name":"卸妆"
                                },
                                {
                                    "img":"assets/img/classify/110.png",
                                    "name":"女士香水"
                                }

                            ]
                        },
                        {
                            "classify":"美发护发",
                            "conList":[
                                {
                                    "img":"assets/img/classify/99.png",
                                    "name":"洗发水"
                                },
                                {
                                    "img":"assets/img/classify/100.png",
                                    "name":"护发素"
                                },
                                {
                                    "img":"assets/img/classify/101.png",
                                    "name":"洗护套装"
                                },
                                {
                                    "img":"assets/img/classify/103.png",
                                    "name":"卷发棒"
                                },
                                {
                                    "img":"assets/img/classify/104.png",
                                    "name":"电吹风"
                                },
                                {
                                    "img":"assets/img/classify/102.png",
                                    "name":"染发"
                                }
                            ]
                        },
                        {
                            "classify":"身体护理",
                            "conList":[
                                {
                                    "img":"assets/img/classify/05889626701031510.jpg",
                                    "name":"私密护理"
                                },
                                {
                                    "img":"assets/img/classify/05889626398551421.jpg",
                                    "name":"手工皂"
                                },
                                {
                                    "img":"assets/img/classify/05889610014611514.jpg",
                                    "name":"美容养颜"
                                },
                                {
                                    "img":"assets/img/classify/05889610872282857.jpg",
                                    "name":"磨砂膏"
                                },
                                {
                                    "img":"assets/img/classify/110.png",
                                    "name":"沐浴露"
                                },
                                {
                                    "img":"assets/img/classify/108.png",
                                    "name":"手足护理"
                                },
                                {
                                    "img":"assets/img/classify/109.png",
                                    "name":"身体乳"
                                },
                                {
                                    "img":"assets/img/classify/105.png",
                                    "name":"香薰精油"
                                },
                                {
                                    "img":"assets/img/classify/113.png",
                                    "name":"卫生巾"
                                },
                                {
                                    "img":"assets/img/classify/106.png",
                                    "name":"纤体瘦身"
                                }
                            ]
                        },
                        {
                            "classify":"美容工具",
                            "conList":[
                                {
                                    "img":"assets/img/classify/137.png",
                                    "name":"美容仪"
                                },
                                {
                                    "img":"assets/img/classify/139.png",
                                    "name":"洁面仪"
                                },
                                {
                                    "img":"assets/img/classify/140.png",
                                    "name":"理发器"
                                },
                                {
                                    "img":"assets/img/classify/133.png",
                                    "name":"剃须刀"
                                },
                                {
                                    "img":"assets/img/classify/132.png",
                                    "name":"剃毛器"
                                },
                                {
                                    "img":"assets/img/classify/134.png",
                                    "name":"喷雾器"
                                },
                                {
                                    "img":"assets/img/classify/138.png",
                                    "name":"美容配件"
                                }
                            ]
                        },
                        {
                            "classify":"口腔护理",
                            "conList":[
                                {
                                    "img":"assets/img/classify/141.png",
                                    "name":"牙刷"
                                },
                                {
                                    "img":"assets/img/classify/145.png",
                                    "name":"牙膏"
                                }
                            ]
                        }
                    ]
                },
                {
                    "title":"食品健康",
                    "content":[
                        {
                            "classify":"面部护理",
                            "conList":[
                                {
                                    "img":"assets/img/classify/93.png",
                                    "name":"面膜"
                                },
                                {
                                    "img":"assets/img/classify/90.png",
                                    "name":"乳液乳霜"
                                },
                                {
                                    "img":"assets/img/classify/94.png",
                                    "name":"精华"
                                },
                                {
                                    "img":"assets/img/classify/96.png",
                                    "name":"护肤套组"
                                },
                                {
                                    "img":"assets/img/classify/97.png",
                                    "name":"防晒隔离"
                                },
                                {
                                    "img":"assets/img/classify/89.png",
                                    "name":"爽肤水"
                                },
                                {
                                    "img":"assets/img/classify/95.png",
                                    "name":"洁面乳"
                                },
                                {
                                    "img":"assets/img/classify/88.png",
                                    "name":"眼部护理"
                                },
                                {
                                    "img":"assets/img/classify/92.png",
                                    "name":"眼膜"
                                }
                            ]
                        },
                    ]
                },
                {
                    "title":"餐厨日用",
                    "content":[
                        {
                            "classify":"面部护理",
                            "conList":[
                                {
                                    "img":"assets/img/classify/93.png",
                                    "name":"面膜"
                                },
                                {
                                    "img":"assets/img/classify/90.png",
                                    "name":"乳液乳霜"
                                },
                                {
                                    "img":"assets/img/classify/94.png",
                                    "name":"精华"
                                },
                                {
                                    "img":"assets/img/classify/96.png",
                                    "name":"护肤套组"
                                },
                                {
                                    "img":"assets/img/classify/97.png",
                                    "name":"防晒隔离"
                                },
                                {
                                    "img":"assets/img/classify/89.png",
                                    "name":"爽肤水"
                                },
                                {
                                    "img":"assets/img/classify/95.png",
                                    "name":"洁面乳"
                                },
                                {
                                    "img":"assets/img/classify/88.png",
                                    "name":"眼部护理"
                                },
                                {
                                    "img":"assets/img/classify/92.png",
                                    "name":"眼膜"
                                }
                            ]
                        },
                    ]
                },
                {
                    "title":"服装配饰",
                    "content":[
                        {
                            "classify":"面部护理",
                            "conList":[
                                {
                                    "img":"assets/img/classify/93.png",
                                    "name":"面膜"
                                },
                                {
                                    "img":"assets/img/classify/90.png",
                                    "name":"乳液乳霜"
                                },
                                {
                                    "img":"assets/img/classify/94.png",
                                    "name":"精华"
                                },
                                {
                                    "img":"assets/img/classify/96.png",
                                    "name":"护肤套组"
                                },
                                {
                                    "img":"assets/img/classify/97.png",
                                    "name":"防晒隔离"
                                },
                                {
                                    "img":"assets/img/classify/89.png",
                                    "name":"爽肤水"
                                },
                                {
                                    "img":"assets/img/classify/95.png",
                                    "name":"洁面乳"
                                },
                                {
                                    "img":"assets/img/classify/88.png",
                                    "name":"眼部护理"
                                },
                                {
                                    "img":"assets/img/classify/92.png",
                                    "name":"眼膜"
                                }
                            ]
                        },
                    ]
                },
                {
                    "title":"布艺家纺",
                    "content":[
                        {
                            "classify":"面部护理",
                            "conList":[
                                {
                                    "img":"assets/img/classify/93.png",
                                    "name":"面膜"
                                },
                                {
                                    "img":"assets/img/classify/90.png",
                                    "name":"乳液乳霜"
                                },
                                {
                                    "img":"assets/img/classify/94.png",
                                    "name":"精华"
                                },
                                {
                                    "img":"assets/img/classify/96.png",
                                    "name":"护肤套组"
                                },
                                {
                                    "img":"assets/img/classify/97.png",
                                    "name":"防晒隔离"
                                },
                                {
                                    "img":"assets/img/classify/89.png",
                                    "name":"爽肤水"
                                },
                                {
                                    "img":"assets/img/classify/95.png",
                                    "name":"洁面乳"
                                },
                                {
                                    "img":"assets/img/classify/88.png",
                                    "name":"眼部护理"
                                },
                                {
                                    "img":"assets/img/classify/92.png",
                                    "name":"眼膜"
                                }
                            ]
                        },
                    ]
                },
                {
                    "title":"家电数码",
                    "content":[
                        {
                            "classify":"面部护理",
                            "conList":[
                                {
                                    "img":"assets/img/classify/93.png",
                                    "name":"面膜"
                                },
                                {
                                    "img":"assets/img/classify/90.png",
                                    "name":"乳液乳霜"
                                },
                                {
                                    "img":"assets/img/classify/94.png",
                                    "name":"精华"
                                },
                                {
                                    "img":"assets/img/classify/96.png",
                                    "name":"护肤套组"
                                },
                                {
                                    "img":"assets/img/classify/97.png",
                                    "name":"防晒隔离"
                                },
                                {
                                    "img":"assets/img/classify/89.png",
                                    "name":"爽肤水"
                                },
                                {
                                    "img":"assets/img/classify/95.png",
                                    "name":"洁面乳"
                                },
                                {
                                    "img":"assets/img/classify/88.png",
                                    "name":"眼部护理"
                                },
                                {
                                    "img":"assets/img/classify/92.png",
                                    "name":"眼膜"
                                }
                            ]
                        },
                    ]
                },
                {
                    "title":"母婴呵护",
                    "content":[
                        {
                            "classify":"面部护理",
                            "conList":[
                                {
                                    "img":"assets/img/classify/93.png",
                                    "name":"面膜"
                                },
                                {
                                    "img":"assets/img/classify/90.png",
                                    "name":"乳液乳霜"
                                },
                                {
                                    "img":"assets/img/classify/94.png",
                                    "name":"精华"
                                },
                                {
                                    "img":"assets/img/classify/96.png",
                                    "name":"护肤套组"
                                },
                                {
                                    "img":"assets/img/classify/97.png",
                                    "name":"防晒隔离"
                                },
                                {
                                    "img":"assets/img/classify/89.png",
                                    "name":"爽肤水"
                                },
                                {
                                    "img":"assets/img/classify/95.png",
                                    "name":"洁面乳"
                                },
                                {
                                    "img":"assets/img/classify/88.png",
                                    "name":"眼部护理"
                                },
                                {
                                    "img":"assets/img/classify/92.png",
                                    "name":"眼膜"
                                }
                            ]
                        },
                    ]
                },
                {
                    "title":"芒果汽车",
                    "content":[
                        {
                            "classify":"面部护理",
                            "conList":[
                                {
                                    "img":"assets/img/classify/93.png",
                                    "name":"面膜"
                                },
                                {
                                    "img":"assets/img/classify/90.png",
                                    "name":"乳液乳霜"
                                },
                                {
                                    "img":"assets/img/classify/94.png",
                                    "name":"精华"
                                },
                                {
                                    "img":"assets/img/classify/96.png",
                                    "name":"护肤套组"
                                },
                                {
                                    "img":"assets/img/classify/97.png",
                                    "name":"防晒隔离"
                                },
                                {
                                    "img":"assets/img/classify/89.png",
                                    "name":"爽肤水"
                                },
                                {
                                    "img":"assets/img/classify/95.png",
                                    "name":"洁面乳"
                                },
                                {
                                    "img":"assets/img/classify/88.png",
                                    "name":"眼部护理"
                                },
                                {
                                    "img":"assets/img/classify/92.png",
                                    "name":"眼膜"
                                }
                            ]
                        },
                    ]
                },
                {
                    "title":"品牌馆",
                    "content":[
                        {
                            "classify":"面部护理",
                            "conList":[
                                {
                                    "img":"assets/img/classify/93.png",
                                    "name":"面膜"
                                },
                                {
                                    "img":"assets/img/classify/90.png",
                                    "name":"乳液乳霜"
                                },
                                {
                                    "img":"assets/img/classify/94.png",
                                    "name":"精华"
                                },
                                {
                                    "img":"assets/img/classify/96.png",
                                    "name":"护肤套组"
                                },
                                {
                                    "img":"assets/img/classify/97.png",
                                    "name":"防晒隔离"
                                },
                                {
                                    "img":"assets/img/classify/89.png",
                                    "name":"爽肤水"
                                },
                                {
                                    "img":"assets/img/classify/95.png",
                                    "name":"洁面乳"
                                },
                                {
                                    "img":"assets/img/classify/88.png",
                                    "name":"眼部护理"
                                },
                                {
                                    "img":"assets/img/classify/92.png",
                                    "name":"眼膜"
                                }
                            ]
                        },
                    ]
                }
            ]
        }
        return data
    }
}
