module.exports = {
    getData(){
        let data = {
            "banner":[
                {"num":1,"src":"assets/img/index/06258536682899389.jpg"},
                {"num":2,"src":"assets/img/index/06258560589978261.png"},
                {"num":3,"src":"assets/img/index/06259177393542712.jpg"},
                {"num":4,"src":"assets/img/index/06259448882801117.jpg"},
                {"num":5,"src":"assets/img/index/06259451090498533.jpg"},
                {"num":6,"src":"assets/img/index/06259460567173608.jpg"}
            ],
            "link":"assets/img/index/06258552617537597.gif",
            "todayAct":{
                "title":"assets/img/index/index_t_1.png",
                "list":[
                    {
                        "actTitle":"assets/img/index/06259440150287217.jpg",
                        "swiperCon":[
                            {
                                "img":"assets/img/index/1_main_9_360.jpg",
                                "title":"佰朗帝浮华宫廷鎏金绵羊皮风衣",
                                "price":"￥1180",
                                "oPrice":"￥1580"
                            },
                            {
                                "img":"assets/img/index/1_main_297480_360.jpg",
                                "title":"LetsDiet经典魔术裤小黑裤修身瘦腿小脚3D提臀设计",
                                "price":"￥148",
                                "oPrice":"￥199"
                            },
                            {
                                "img":"assets/img/index/1_main_286521_360.jpg",
                                "title":"尚街瑰丽设计师款云绒针织连衣裙",
                                "price":"￥159",
                                "oPrice":"￥209"
                            },
                            {
                                "img":"assets/img/index/1_main_11_360.jpg",
                                "title":"Merefa爱丽小香风珠彩粗花呢长款外套",
                                "price":"￥349",
                                "oPrice":"￥399"
                            },
                            {
                                "img":"assets/img/index/1_main_276293_360.jpg",
                                "title":"尚街瑰丽设计师款云绒针织女装实惠组合",
                                "price":"￥99",
                                "oPrice":"￥109"
                            },
                            {
                                "img":"assets/img/index/1_main_9_360 (1).jpg",
                                "title":"心姬塑型无钢圈无海绵大码内衣（4件组合）",
                                "price":"￥219",
                                "oPrice":"￥229"
                            },
                            {
                                "img":"assets/img/index/1_main_280636_360.jpg",
                                "title":"优廷繁星复古丝绒时装裤套组（阔腿裤*1件+直筒裤*1件+打底裤*1件）",
                                "price":"￥219",
                                "oPrice":"￥229"
                            }
                        ]
                    },
                    {
                        "actTitle":"assets/img/index/06259440150287217.jpg",
                        "swiperCon":[
                            {
                                "img":"assets/img/index/1_main_9_360.jpg",
                                "title":"LetsDiet经典魔术裤小黑裤修身瘦腿小脚3D提臀设计",
                                "price":"￥148",
                                "oPrice":"￥199"
                            },
                            {
                                "img":"assets/img/index/1_main_9_360.jpg",
                                "title":"LetsDiet经典魔术裤小黑裤修身瘦腿小脚3D提臀设计",
                                "price":"￥148",
                                "oPrice":"￥199"
                            },
                            {
                                "img":"assets/img/index/1_main_9_360.jpg",
                                "title":"LetsDiet经典魔术裤小黑裤修身瘦腿小脚3D提臀设计",
                                "price":"￥148",
                                "oPrice":"￥199"
                            },
                            {
                                "img":"assets/img/index/1_main_9_360.jpg",
                                "title":"LetsDiet经典魔术裤小黑裤修身瘦腿小脚3D提臀设计",
                                "price":"￥148",
                                "oPrice":"￥199"
                            }
                        ]
                    }

                ]
            }
        }
        return data
    }
}
